#!/bin/bash

set -e;

if [ ! -d "$HOME/.scripts" ]; then
    echo "projects dir does not exist"
    exit 1;
fi

selected="$(find $HOME/projects -maxdepth 1 -mindepth 1 | fzf)"

kitty -d $selected --detach

cd $selected
nvim .
